const quizData = [
  {
    que: "What is the size of byte variable?",
    a: "8 bit",
    b: "16 bit",
    c: "32 bit",
    d: "64 bit",
    correct: "a",
  },
  {
    que: "What is the default value of double variable?",
    a: "0.0d",
    b: "0.0f",
    c: "0",
    d: "not defined",
    correct: "a",
  },
  {
    que: "Method Overloading is an example of",
    a: "Static Binding.",
    b: "Dynamic Binding.",
    c: "Both of the above.",
    d: "None of the above.",
    correct: "a",
  },
  {
    que: "In which case, a program is expected to recover?",
    a: "If an error occurs.",
    b: "If an exception occurs.",
    c: "Both of the above.",
    d: "None of the above.",
    correct: "b",
  },
  {
    que: "Who invented Java Programming?",
    a: "Guido van Rossum",
    b: "James Gosling",
    c: "Dennis Ritchie",
    d: "Bjarne Stroustrup",
    correct: "b",
  },
  {
    que: "Which one of the following is not a Java feature?",
    a: "Object-oriented",
    b: "Use of pointers",
    c: "Portable",
    d: "Dynamic and Extensible",
    correct: "b",
  },
  {
    que: "Which exception is thrown when java is out of memory?",
    a: " MemoryError",
    b: "OutOfMemoryError",
    c: "MemoryOutOfBoundsException",
    d: "MemoryFullException",
    correct: "b",
  },
  {
    que: "Which of these are selection statements in Java?",
    a: "break",
    b: "continue",
    c: "for()",
    d: "if()",
    correct: "d",
  },
  {
    que: "Which of the following is a superclass of every class in Java?",
    a: "ArrayList",
    b: "Abstract class",
    c: "Object class",
    d: "String",
    correct: "c",
  },
  {
    que: "What is the numerical range of a char data type in Java?",
    a: "0 to 256",
    b: "-128 to 127",
    c: "0 to 65535",
    d: "0 to 32767",
    correct: "c",
  },
];
